# Generated by Django 5.2.4 on 2026-05-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_notice', '0003_user_role_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
