# Generated by Django 5.2.4 on 2026-05-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo_notice', '0004_alter_notice_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
