# Generated by Django 5.2.4 on 2026-05-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('neo_notice', '0005_remove_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AdminModel',
        ),
    ]
