# Generated by Django 5.2.4 on 2026-05-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo_notice', '0007_rename_adminmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
